export const GET_ERRORS = 'GET_ERRORS'
export const USER_LOADING = 'USER_LOADING'
export const SET_CURRENT_USER = 'SET_CURRENT_USER'
export const GET_ALL_LINKS = 'GET_ALL_LINKS'
export const ADD_NEW_LINK = 'ADD_NEW_LINK'
export const UPDATE_LINK = 'UPDATE_LINK'
export const DELETE_LINK = 'DELETE_LINK'
export const LOG_OUT = 'LOG_OUT'
